In [1]:
import numpy as np
from utils import *
import pandas as pd

In [210]:
data = pd.read_table("data/web_crowd.txt",header=None)

In [211]:
truth = pd.read_table("data/web_truth.txt", header=None)


In [195]:
def transform_data(data):
    X = np.array(data)
    rows, _ = X.shape
    n,m,k = np.max(np.array(data), axis=0)
    labels = np.zeros((m,n),dtype=np.int64)-1
    for r in range(rows):
        labels[X[r,1]-1,X[r,0]-1] = X[r,2]-1
    return labels


In [212]:
transform_data(data)


array([[ 4,  0,  0, ..., -1, -1, -1],
       [ 4, -1,  0, ...,  2,  1, -1],
       [ 4, -1, -1, ..., -1,  3, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]], dtype=int64)

In [213]:
n,m,k = np.max(np.array(data),axis=0)
print(n,m,k)

2665 177 5


In [214]:
labels = transform_data(data)


In [215]:
labels


array([[ 4,  0,  0, ..., -1, -1, -1],
       [ 4, -1,  0, ...,  2,  1, -1],
       [ 4, -1, -1, ..., -1,  3, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]], dtype=int64)

In [216]:
C_estimated = get_confusion_matrix(k,labels,sym=False)

In [217]:
data[data[1]==1]

0  1  2
0         1  1  5
6         2  1  1
12        3  1  1
18        4  1  1
24        5  1  2
...     ... .. ..
15477  2651  1  5
15489  2653  1  4
15501  2655  1  5
15525  2659  1  3
15543  2662  1  3

[1044 rows x 3 columns]

In [218]:
truth

0  1
0        1  5
1        2  1
2        3  1
3        4  1
4        5  2
...    ... ..
2648  2661  5
2649  2662  2
2650  2663  4
2651  2664  3
2652  2665  4

[2653 rows x 2 columns]

In [219]:
from sklearn.metrics import confusion_matrix


In [220]:
truth_new = truth[truth[0].isin(data[data[1] == 2][0])]
pred_new = data[data[1] == 2][data[data[1] == 2][0].isin(truth_new[0])]


In [221]:
truth_new


0  1
0        1  5
2        3  1
4        5  2
9       10  5
11      12  1
...    ... ..
2630  2643  5
2636  2649  5
2638  2651  5
2650  2663  4
2651  2664  3

[784 rows x 2 columns]

In [222]:
pred_new

0  1  2
1         1  2  5
13        3  2  1
25        5  2  2
52       10  2  5
64       12  2  1
...     ... .. ..
15430  2643  2  5
15467  2649  2  5
15478  2651  2  2
15549  2663  2  3
15555  2664  2  2

[784 rows x 3 columns]

In [223]:
C = confusion_matrix(pred_new[2],truth_new[1])

In [224]:
C / np.sum(C,axis=0)[np.newaxis,:]

array([[0.84946237, 0.19565217, 0.07327586, 0.01986755, 0.02352941],
       [0.12903226, 0.7173913 , 0.10775862, 0.11258278, 0.04705882],
       [0.        , 0.07971014, 0.75862069, 0.25165563, 0.06470588],
       [0.        , 0.00724638, 0.04310345, 0.54304636, 0.04117647],
       [0.02150538, 0.        , 0.01724138, 0.07284768, 0.82352941]])

In [225]:
C_estimated[1]

array([[ 0.2289891 ,  0.18040218,  0.0170882 , -0.00292867,  0.01763028],
       [ 0.05609443,  0.39020321,  0.04761515,  0.01734353,  0.01481299],
       [-0.06441023, -0.42467619,  0.15631743,  0.10064339,  0.02681516],
       [-0.00667989, -0.17706989,  0.03419089,  0.11966267,  0.02245573],
       [ 0.78600658,  1.03114068,  0.74478834,  0.76527908,  0.91828585]])

In [226]:
m, n = labels.shape


In [227]:
np.random.seed(0)
groups = np.random.randint(3, size=m)


In [247]:
groups = np.array([i%3 for i in range(m)])

In [248]:
groups


array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2])

In [249]:
Zg = get_Zg(k, labels, groups)


In [250]:
Zg

array([[[0.        , 0.        , 0.        , 0.        , 0.03389831],
        [0.05084746, 0.        , 0.        , 0.        , 0.        ],
        [0.03389831, 0.        , 0.        , 0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , 0.01694915, 0.        ],
        [0.        , 0.        , 0.01694915, 0.        , 0.        ],
        [0.        , 0.        , 0.01694915, 0.01694915, 0.        ]],

       [[0.        , 0.        , 0.        , 0.        , 0.03389831],
        [0.01694915, 0.        , 0.        , 0.        , 0.        ],
        [0.03389831, 0.        , 0.        , 0.        , 0.01694915],
        ...,
        [0.        , 0.        , 0.01694915, 0.01694915, 0.03389831],
        [0.        , 0.01694915, 0.        , 0.01694915, 0.        ],
        [0.        , 0.        , 0.        , 0.03389831, 0.01694915]],

       [[0.        , 0.        , 0.        , 0.        , 0.03389831],
        [0.03389831, 0.        , 0.        , 0.        , 0. 

In [251]:
Z = np.zeros((m,n,k))

In [252]:
for i in range(len(data)):
    Z[data.iloc[i, 1]-1, data.iloc[i, 0]-1, data.iloc[i, 2]-1] = 1


In [253]:
Zg = np.zeros((3,n,k))
for g in range(3):
    Zg[g,:,:] = np.mean(Z[groups==g,:,:],axis=0)

In [254]:
np.all(Zg == get_Zg(k, labels, groups))

True

In [255]:
M2s, M3s = get_M(Zg)


In [257]:
M3s

[array([[[1.06549972e-06, 4.00909567e-07, 1.86179973e-07, 6.24276453e-08,
          1.03600769e-07],
         [2.54174415e-07, 4.46648428e-07, 1.40646002e-07, 7.01520550e-08,
          1.77188614e-07],
         [2.36062713e-07, 1.11559407e-07, 1.74379658e-07, 1.00333511e-07,
          1.17523448e-07],
         [5.52842310e-08, 6.02824313e-08, 1.31176047e-07, 2.14339296e-08,
          7.79550528e-08],
         [5.39319191e-08, 1.07918096e-07, 1.30878074e-07, 1.41321823e-07,
          2.78167546e-07]],
 
        [[3.37570139e-07, 3.50205452e-07, 1.47750442e-07, 1.00946691e-07,
          1.26257788e-07],
         [3.57496434e-07, 1.13783132e-06, 5.66940033e-07, 2.62104108e-07,
          1.53713051e-07],
         [1.10026953e-07, 4.33278892e-07, 4.48427205e-07, 2.72991611e-07,
          1.78693951e-07],
         [8.98954393e-08, 2.25697396e-07, 1.88496372e-07, 1.36317728e-07,
          1.52921146e-07],
         [1.52980207e-07, 2.17240718e-07, 1.19820034e-07, 7.11922876e-08,
          3.12